# Generated by Django 3.1.4 on 2021-01-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('get_url', models.CharField(max_length=30)),
                ('icon_path', models.CharField(max_length=50)),
            ],
        ),
    ]
