# Generated by Django 3.1.4 on 2021-01-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchengine',
            name='get_url',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='searchengine',
            name='icon_path',
            field=models.CharField(max_length=100),
        ),
    ]
