# Generated by Django 3.1.5 on 2021-01-29 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query_builder', '0002_auto_20210112_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_construct', models.CharField(max_length=128, verbose_name='search parameter key and syntax')),
                ('extra_tips', models.CharField(blank=True, max_length=256, verbose_name='tips for usage in specific engine')),
            ],
        ),
        migrations.CreateModel(
            name='SearchSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=64, unique=True, verbose_name="the most adequate setting's name")),
                ('ascriptors', models.CharField(blank=True, max_length=256, verbose_name='verbal equivalents to descriptor')),
                ('description', models.TextField()),
                ('tips', models.CharField(blank=True, max_length=256, verbose_name='general clues for using specific setting')),
            ],
            options={
                'ordering': ['descriptor'],
            },
        ),
        migrations.AlterModelOptions(
            name='searchengine',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='searchengine',
            name='get_url',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='searchengine',
            name='icon_path',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='searchengine',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='SettingValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('human_readable', models.CharField(max_length=128)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_builder.searchsetting')),
            ],
        ),
        migrations.AddField(
            model_name='searchsetting',
            name='engine',
            field=models.ManyToManyField(through='query_builder.Invocation', to='query_builder.SearchEngine'),
        ),
        migrations.AddField(
            model_name='invocation',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_builder.searchengine'),
        ),
        migrations.AddField(
            model_name='invocation',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_builder.searchsetting'),
        ),
    ]
