# Generated by Django 3.1.5 on 2021-02-01 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query_builder', '0003_auto_20210129_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingvalue',
            name='setting',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='query_builder.searchsetting'),
        ),
    ]
