# Generated by Django 3.1.4 on 2021-02-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_builder', '0004_auto_20210201_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invocation',
            options={'ordering': ['setting']},
        ),
    ]
